remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-theme-minimal # add this line to the plugins list if you already have one
- jekyll-sitemap
- jekyll-seo-tag
title: [HunterX Threat Intelligence Lab]
description: [Cyber Threat Intelligence blog analyzing malware, phishing campaigns, OSINT investigations, and threat actors.]
